[package]
name = "poseidon-consistency"
version = "0.1.0"
edition = "2018"
authors = ["Penumbra <crates@penumbra.zone>", "redshiftzero <jen@penumbra.zone>"]
description = "Checks consistency between Penumbra and Ark-sponge implementation"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poseidon-paramgen = { version="0.1" }
poseidon-permutation = {version= "0.1", path="../poseidon-permutation/"}
ark-sponge = { version="0.3", git = "https://github.com/penumbra-zone/sponge", branch = "r1cs" }
decaf377 = "0.1"

[dev-dependencies]
criterion = { version = "0.3", features=["html_reports"] }
ark-ff = "0.3"
ark-ed-on-bls12-377 = "0.3"
num-bigint = "0.4"
proptest = "1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand_chacha = "0.3"
once_cell = "1.8"

[[bench]]
name = "permutation"
harness = false
